services:
  server:
    image: simona4220/suncoder-job-server
    ports:
     - "1234:1234"
    networks:
     - back-tier
  worker:
    depends_on:
      - server
    image: simona4220/suncoder-job-worker
    deploy:
      replicas: 1
    networks:
      - back-tier
  db:
    container_name: db
    image: mariadb
    ports:
     - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=mypass
    volumes:
      - /var/lib/docker/volumes/mariadb:/var/lib/mysql
networks:
  back-tier: {}
