apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  api_url: "//suncoder.proj.cs.sun.ac.za:443"
  nginx_url: "suncoder-api.proj.cs.sun.ac.za"
  front_end_port: "443"
  mariadb_url: mariadb-service
  job_server_port: "1234"
  jserver_url: jserver-service
