window._env_ = {
  TERM_PROGRAM: "vscode",
  _P9K_TTY: "/dev/ttys000",
  TERM: "xterm-256color",
  SHELL: "/bin/zsh",
  TMPDIR: "/var/folders/8z/ptq6kvxn293_9yynrzf7rnwc0000gn/T/",
  CONDA_SHLVL: "1",
  TERM_PROGRAM_VERSION: "1.71.0",
  CONDA_PROMPT_MODIFIER: "(base) ",
  ZDOTDIR: "/var/folders/8z/ptq6kvxn293_9yynrzf7rnwc0000gn/T/vscode-zsh",
  ORIGINAL_XDG_CURRENT_DESKTOP: "undefined",
  MallocNanoZone: "0",
  ZSH: "/Users/simon/.oh-my-zsh",
  USER: "simon",
  COMMAND_MODE: "unix2003",
  CONDA_EXE: "/Users/simon/miniforge3/bin/conda",
  SSH_AUTH_SOCK: "/private/tmp/com.apple.launchd.8gCxoC5RsF/Listeners",
  __CF_USER_TEXT_ENCODING: "0x1F5:0x0:0x0",
  PAGER: "less",
  _CE_CONDA: "",
  LSCOLORS: "Gxfxcxdxbxegedabagacad",
  PATH: "/usr/local/mysql-8.0.28-macos11-arm64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql-8.0.28-macos11-arm64/bin:/Users/simon/miniforge3/bin:/Users/simon/miniforge3/condabin:/opt/homebrew/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/opt/homebrew/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin",
  LaunchInstanceID: "523D8244-92FB-4CF8-A017-E198FA5ECB1C",
  CONDA_PREFIX: "/Users/simon/miniforge3",
  __CFBundleIdentifier: "com.microsoft.VSCode",
  PWD: "/Users/simon/Developer/Honours_project/suncoder",
  JAVA_HOME: "/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home",
  P9K_SSH: "0",
  P9K_TTY: "old",
  LANG: "en_GB.UTF-8",
  VSCODE_GIT_ASKPASS_EXTRA_ARGS: "--ms-enable-electron-run-as-node",
  XPC_FLAGS: "0x0",
  _CE_M: "",
  XPC_SERVICE_NAME: "0",
  VSCODE_INJECTION: "1",
  SHLVL: "2",
  HOME: "/Users/simon",
  VSCODE_GIT_ASKPASS_MAIN: "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  REDIRECT_PORT: "3000",
  CONDA_PYTHON_EXE: "/Users/simon/miniforge3/bin/python",
  LESS: "-R",
  LOGNAME: "simon",
  VSCODE_GIT_IPC_HANDLE: "/var/folders/8z/ptq6kvxn293_9yynrzf7rnwc0000gn/T/vscode-git-8f96262b54.sock",
  CLASSPATH: ".:/usr/local/lib/antlr-4.9.2-complete.jar:/usr/local/lib/stdlib.jar:/usr/local/lib/algs4.jar:.:/usr/local/lib/antlr-4.9.2-complete.jar:/usr/local/lib/stdlib.jar:/usr/local/lib/algs4.jar:",
  CONDA_DEFAULT_ENV: "base",
  VSCODE_GIT_ASKPASS_NODE: "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper",
  GIT_ASKPASS: "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  SECURITYSESSIONID: "186b2",
  COLORTERM: "truecolor",
  _: "/usr/bin/printenv",
}
